### ISSUE TITLE
Add Alarm pop-up window below option

### ISSUE THREAD

**Issue by Gaiiden** [TriggerAu/KerbalAlarmClock#106]
This is the best layout I can come up with, the problem is that the Add Alarm window partially covers the center UI widget and they fight for control when you bring the mouse over. Generally the UI widget wins and I have trouble getting the last three alarm buttons as well as the button to expand the details box. Perhaps the option to have the Add Alarm window appear beneath the main window? Yes, I have the option enabled to disable click-throughs

![ksp exe_dx9_20150113_113551](https://cloud.githubusercontent.com/assets/7699577/5720404/9d121ec4-9af1-11e4-8f7a-c5eb97018e24.png)

**Comment by TriggerAu** [comment]
Should be doable, let me see how I can fit it in
