### ISSUE TITLE
Show date of alarm instead of just time remaining

### ISSUE THREAD

**Issue by Gaiiden** [TriggerAu/KerbalAlarmClock#107]
This blank space in the alarm details window would be good for the date/time of the alarm in addition to the time remaining. Or, since the time remaining is already shown in the Alarm List, just have the date/time of the alarm rather than repeating information

![ksp exe_dx9_20150113_124412](https://cloud.githubusercontent.com/assets/7699577/5720877/3e4595cc-9af8-11e4-9bc7-1ab30a8da02c.png)

**Comment by TriggerAu** [comment]
Good idea - I have a recollection of that being there at some point - maybe I dropped it in v3. Will get it in there

**Comment by Gaiiden** [comment]
nope this was never there, however it has been suggested on the forum a few times so I decided to just cut to the chase and log it here :)

**Comment by TriggerAu** [comment]
Found it - in one of my v3 restarts, but missed it when I mashed em all together.  Will get it in the next release - hopefully this weekend

**Comment by TriggerAu** [comment]
So the left hand side there shos the Time to the Alarm currently when there are margins - if I'm reading this code on the train right :)

I had the Date showing below the time to event (as event date) in this file - I'll add that to th ewindow and see what it looks like - from memory it was OK down there
