### ISSUE TITLE
NullReferenceException: KerbalAlarmClock.KerbalAlarmClock.FillAlarmWindow

### ISSUE THREAD

**Issue by WuphonsReach** [TriggerAu/KerbalAlarmClock#122]
These mostly seem to happen in conjunction with Kerbal Construction Time when using the "warp to" button to finish up a build or launchpad reconditioning.  Not sure if KCT is calling KAC with garbage or if the error is within KCT.

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/9/2015 4:29:08 PM,KerbalAlarmClock,Reducing Warp-Transition
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/9/2015 4:29:08 PM,KerbalAlarmClock,Triggering Alarm - KCT: Tethys I (Karbonite) Complete
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/9/2015 4:29:08 PM,KerbalAlarmClock,KCT: Tethys I (Karbonite) Complete-Halt Warp
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/9/2015 4:29:08 PM,KerbalAlarmClock,Actioning Alarm
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

Unpacking Thlassa I (High Orbit) Y1D199 Duna
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

3/9/2015 4:29:08 PM,KerbalAlarmClock,API-DeleteAlarm-Deleting:33f6410d043f4ddb9f7f072aa6f0b30b
 
(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

NullReferenceException: Object reference not set to an instance of an object
  at KerbalAlarmClock.KerbalAlarmClock.FillAlarmWindow (Int32 windowID) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID) [0x00000] in <filename unknown>:0 

  at UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style) [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

**Comment by TriggerAu** [comment]
Interesting, Just it just fire the once, or does it continue on after that?

**Comment by TriggerAu** [comment]
Any info on this one?

**Comment by TriggerAu** [comment]
Any more info on it - or do we close it off and see what 1.0.x is like?

**Comment by TriggerAu** [comment]
Cant replicate myself currently
