### ISSUE TITLE
automatic alarm and "warp to" alarm

### ISSUE THREAD

**Issue by abenkovskii** [TriggerAu/KerbalAlarmClock#124]
It would be nice to have an option to remove automatic alarm when using "warp to" to the same point of orbit.

**Comment by TriggerAu** [comment]
Hmm, it should already do that... maybe it needs to be an exact time, I'll fiddle it here

**Comment by TriggerAu** [comment]
Was only working for Manual Alarms, thanks for the issue log. Have resolved it in the attached commit and will be in the next release
