### ISSUE TITLE
Date of Event shows alarm time, not event time

### ISSUE THREAD

**Issue by Gaiiden** [TriggerAu/KerbalAlarmClock#126]
![ksp exe_dx9_20150404_122524](https://cloud.githubusercontent.com/assets/7699577/6992573/8f8bc938-daa4-11e4-9f6f-b7e778678fdc.png)
The actual time of this maneuver node event is supposed to be 12:00:00 but I have the alarm set to trigger 15min prior.

**Comment by TriggerAu** [comment]
Found it.
