### ISSUE TITLE
KAC does not stop the warp completely if stock's Warp Here command was issued.

### ISSUE THREAD

**Issue by ZiwKerman** [TriggerAu/KerbalAlarmClock#132]
I've encountered this one while trying to add WarpTo function to kOS and unfortunately do not have any solution/suggestions on how to fix that. The only way to stop the warp is to press Esc it seems.

**Comment by ZiwKerman** [comment]
To save you some time here's our findings so far:
1) setting warp rate to 0 via `TimeWarp.SetRate(0, false)` does not stop it
2) it seems like there is a Coroutine `private IEnumerator autoWarpTo (double tgtUT, double maxTimeWarping, double minTimeWarping);`, but calling `TimeWarp.fetch.StopCoroutine("autoWarpTo");` does nothing as well.

**Comment by TriggerAu** [comment]
the built in KSP warpto function you mean?

**Comment by ZiwKerman** [comment]
Yes

**Comment by TriggerAu** [comment]
Yeah this one is totally annoying

**Comment by ZiwKerman** [comment]
We gave up on it, until Squad introduces a proper way to stop it in API

**Comment by TriggerAu** [comment]
I'll log a ticket in the testing tracker and raise it with Ted, its painful. Do you have a github issue in your project for it too and I can link em both

**Comment by ZiwKerman** [comment]
It was a planned feature to be added as new built-in function in KOS, so there is no issue yet, but if you want, I can create on.

**Comment by TriggerAu** [comment]
K, I've got an issue logged and chatted with Ted about it, It seems in my head an easy bit of code to disengage the controller if someone calls SetRate , I'll push where I can

**Comment by arechsteiner** [comment]
@TriggerAu: Maybe instead of cancelling a running stock warp, it would be possible to prevent it from happening altogether?

If you could intercept all "Warp here" / "Warp to next maneuver" when they happen and check if within the planned warp duration an alarm is scheduled, then prevent the stock warp from initiating.

I'm not familiar with Kerbal modding but maybe this is a possible workaround, if the modding possibilities allow for it.

**Comment by TriggerAu** [comment]
Woops, didnt see this comment till now, sorry. The new "Warp Here" functionality in KSP has very little exposed to modders. I've raised a request or two to get some publically accessible bits of code for modders, and am also looking for some alterntives in teh meantime
