### ISSUE TITLE
Alarm on MechJeb Rover Waypoints

### ISSUE THREAD

**Issue by palaslet** [TriggerAu/KerbalAlarmClock#134]
Would it be possible to implement a new alarm type that is triggered by MechJeb waypoints from the rover autopilot?

**Comment by TriggerAu** [comment]
Unfortunately I dont think I can do this one. All the alarms are based on projected times - ie when something will happen based on orbital paths.

Are the mechjeb waypoints like that, or they fire when you reach a certain spot?

**Comment by palaslet** [comment]
After using the Rover Autopilot a bit, I can see that the rovers have way to inconsistent velocity due to terrain changes. Estimating a 2-3 hour run is generally 10-20 minutes wrong, so the alarm clock wouldn't help :)
