### ISSUE TITLE
Alarm for Science Lab full

### ISSUE THREAD

**Issue by TriggerAu** [TriggerAu/KerbalAlarmClock#136]

**Comment by Ruedii** [comment]
This would be good.

It should be fairly easy to calculate provided that the lab isn't in an orbit that transitions two science multipliers.

**Comment by mwerle** [comment]
Caveat: I haven't played around with this alarm type yet, nor looked at the code, so apologies if it's generic enough already.

I'm currently investigating adding KAC integration to NEOS.  Experiments in NEOS run for an extended period and I'd like to be able to automatically create alarms and the "ScienceLab" alarm type caught my eye while reading the API docs.

Would it be possible to generalise this alarm type to anything science-related or is it hard-coded for this particular event?

**Comment by TriggerAu** [comment]
thios one is done and think we have solved the margin thing
