### ISSUE TITLE
fontsize weirdness

### ISSUE THREAD

**Issue by valuial** [TriggerAu/KerbalAlarmClock#137]
I'm using KAC on linux and for some reason the fontsize used in all interfaces is bigger than I am used to under windows.
Normally that wouldn't be a problem, but it messes up the window sizes of mod-GUIs.
In the KerbalAlarmClock window starting with two alarms there is always one less alarm visible no matter to how many alarms before scrolling I set the config. So with two alarms there is only one line visible and I need to use the scrollbar to see the second alarm - even when I configure KAC to show 10 alarms before scrolling.

I've confirmed this behaviour with a fresh copy of vanilla KSP and just installing KAC using ckan

Versions of used programs:
KSP 1.0.2
CKAN v1.6.16 started using mono-3.12.1
KAC v3.3.2.1

![screenshot1](https://cloud.githubusercontent.com/assets/12469889/7766751/c3f44eb4-006c-11e5-9a05-7e1387a8d691.png)
![screenshot2](https://cloud.githubusercontent.com/assets/12469889/7766754/c9ad5cd8-006c-11e5-8c92-0766274d6141.png)
![screenshot3](https://cloud.githubusercontent.com/assets/12469889/7766755/cdbc97ee-006c-11e5-83ff-df4797973651.png)

**Comment by TriggerAu** [comment]
Thats certainly not right - can you tell me if it started to do this recently, especially if it happened in v3.3.1.1?

**Comment by valuial** [comment]
Unfortunately not, as I just switched between systems, and didn't realize the problem until then.
What I can report is that KAC seems not to bee the only mod with problems: Others have line-breaks in weird places, like the two-line "Current Time" in my screenshots.
Unfortunately I have no experience with mono/Unity and can't say if any system setting might change the fonts used in KSP, to be responsible.

**Comment by TriggerAu** [comment]
Thanks for the update, I'll have to see if I can dig out a linux instance and see whats going on there. I do recall some Font weirdness with Linux and KSP - so it may be something more general like you mentioned other mods.

Sal wrote a very good summary of a bunch of Linux stuff here - http://forum.kerbalspaceprogram.com/threads/24529-The-Linux-compatibility-thread! - which includes some font stuff. Can I get you to check the font info in there as well?

**Comment by valuial** [comment]
The LC options were not the problem, but the missing font was. Squad uses a Microsoft specific font without bundling it in the game, which breaks the portability of mono.
I'll look into the licensing stuff, but I personally don't like the idea of installing unlicensed font stuff. Much has happened since the 90's but then it was problematic using windows fonts with linux - on a license bases. Technically it's no problem, ofc. For now it works fine.

**Comment by TriggerAu** [comment]
To be totally honest I simply knew the thread was there abiout all things Linux, but have never needed it myself. If its a licensing breach to have that happen then Squad need to get on top of that.

**Comment by TriggerAu** [comment]
BTW, thanks for the responses, I appreciate people working with me on issues :)

**Comment by valuial** [comment]
Same here. Its refreshing to see developers help you figure out problems.

The licensing stuff. Someone put the fonts on the internet without stating under which license. A lot of linux variants offer those as option. Again - noone states with which license or under what conditions they may be used.
The only thing I've found is that someone offered them on sourceforge.net, where the linux pagages get it from. But the only statement there is something like "as far as I know I am allowed to to this".

I can't confirm that the use is legal, but I also cannot confirm that its against Microsofts licensing. I think I will talk to some ppl. from Gentoo - my Linux Distribution - about it. They are usually pretty on point what licensing is concerned...

**Comment by TriggerAu** [comment]
Do let me know what you find, if there is any greyness I can raise it in the QA team and hopefully get any greyness cleared up :)

**Comment by TriggerAu** [comment]
Do let me know what you find, if there is any greyness I can raise it in the QA team and hopefully get any greyness cleared up :)

**Comment by valuial** [comment]
I tried to geet as far upstream as possible. I didn't find any statement or license from Microsoft, but the farthest I got is this project:
http://sourceforge.net/projects/corefonts/

which licenses itself under the GPL (since 2001).

My conclusion:
Microsoft should have responded by now if there is anything they have against it. So no indication that it breaks Microsofts license.
I didn't find any proof that it is within the license, though.

**Comment by valuial** [comment]
Correction, wikipedia has more info:
http://en.wikipedia.org/wiki/Core_fonts_for_the_Web

That should clear it up. It is freeware but only the fonts up to the version they had in 2002. any newer version of these fonts is again closed to the open community.
