### ISSUE TITLE
How to disable "warp shortcuts"?

### ISSUE THREAD

**Issue by arechsteiner** [TriggerAu/KerbalAlarmClock#144]
After installing KerbalAlarmClock, these "fast forward" icons showed up in all my trajectories: 

http://i.imgur.com/NnkBv40.png

Is there a way to disable them? They do more harm than good. I'd prefer KerbalAlarmClock to be less intrusive. Stopping warp on alarm is one thing but adding buttons that ignite a warp without confirmation when fiddling with a maneuver node is not appreciated at all.

PS: Your mod is great otherwise. Saves me a lot of headache. Thanks for writing it and putting it on GitHub!

**Comment by TriggerAu** [comment]
In the settings under "Specific Alarms"->"Warp To Alarms" are all the settings for these, you can disable em in there, as well as enable a confirmation option if you want em there, but two clicks required.

![image](https://cloud.githubusercontent.com/assets/3683611/8172282/6b57f6e4-1402-11e5-91a4-5ccae29c9671.png)

Let me know if theres some other settings you think are needed

**Comment by TriggerAu** [comment]
Closing this one now
