### ISSUE TITLE
store volatile data in a "PluginData" subfolder

### ISSUE THREAD

**Issue by Schnobs** [TriggerAu/KerbalAlarmClock#155]
ModuleManager will rebuild it's ConfigCache whenever something changes in the Gamedata directory. It ignores folders named "PluginData" and everything inside, but any other changed file will trigger a cache rebuild.

Like, /TriggerTech/KerbalAlarmClock/settings.cfg which changes whenever one sets or deletes an alarm. Which I'm in a habit of doing.

**Comment by Galenmacil** [comment]
I support that! 

Read this for more information: https://github.com/m4v/RCSBuildAid/issues/32
