### ISSUE TITLE
Display of Days/Hours/Minutes/Seconds inconsistent with Kerbin days

### ISSUE THREAD

**Issue by sbeitzel** [TriggerAu/KerbalAlarmClock#156]
In stock KSP, time until node will use days/hours/minutes/seconds based on the Kerbin 6-hour day, and other mods use this same convention. However, in KerbalAlarmClock, when we see an event scheduled for 1 day, 2 hours from now it really means that the event is 26 hours in the future. This can lead to confusion and missed opportunities, as when comparing a maneuver node that takes place in 1 day and 2 hours (8 hours in the future) with an alarm in 1 day and 2 hours.

Suggested fix: KerbalAlarmClock uses Kerbin 6 hour days.

**Comment by Ruedii** [comment]
There is currently an option to switch between earth time convention and kerbin time convention.

I agree it should at least take this queue from KSP if not have KSP handle the conversion for the purpose of compatibility with other time based mods.

**Comment by TriggerAu** [comment]
I'll give it a look when I get some time. From memory it should be using the game setting unless its overridden, but thats just my vague tired memory

**Comment by Ruedii** [comment]
It was using game settings for me too.  Is it possible the person in
question had old or corrupted configuration somewhere?

**Comment by sbeitzel** [comment]
I suppose it's possible. In which file might I look to discover such a configuration setting?

**Comment by TriggerAu** [comment]
This seems to be working here, you do need to toggle the calendar setting in KAC currently. This might change when I get nathans request in place for the datetime formatter if it can then use the game setting, but for now gonna close this one out

Apologies for teh slowness

![image](https://cloud.githubusercontent.com/assets/3683611/16331883/5a093ac8-3a36-11e6-9353-aece11783e27.png)
