### ISSUE TITLE
Use negative timespans for future dates / update to 1.1's datetime methods

### ISSUE THREAD

**Issue by NathanKell** [TriggerAu/KerbalAlarmClock#157]
You _may_ already do this, in which case disregard, but if not I would ask you to use a negative UT timespan whenever you are getting the time difference between the current time and a future date. This is because the time formatter in RSS will take leap years into account, and this means it must distinguish whether a timespan is going forwards or backwards from the current UT.

Also, the existing date/time handling should IMO be removed, instead letting any mod changing the date-time-printer interface in KSP handle timespan printing. But let's be clear, it's served well for a long time, for which the whole RSS/RO community is very grateful. :)

Instead, I would ask that KAC support changing between delta display, raw seconds display, and absolute date display (PrintDate() ).

**Comment by NathanKell** [comment]
Bumping this. Give me a holler when you're free, would love to touch base on this (and possibly do some/most of the work for you, since that seems only fair).

**Comment by TriggerAu** [comment]
@NathanKell ready to give this a crack if you have some time over the weekend... just let me know

**Comment by TriggerAu** [comment]
Closing this one with the Kronometer changes in #211
