### ISSUE TITLE
Request to move the settings.cfg to /KerbalAlarmClock/PluginData

### ISSUE THREAD

**Issue by enceos** [TriggerAu/KerbalAlarmClock#166]
The settings.cfg file of KAC stores volatile data. ModuleManager vacuums settings.cfg files into its config cache, which is completely unnecessary because the cache is meant for constant configs. Any change to this file forces ModuleManager to rebuild its cache on each game start. If you move the path for the settings.cfg to the **/KerbalAlarmClock/PluginData** MM will avoid caching that folder, this will speed up the game loading time for all the users.

Same story with any mod which stores volatile data in .cfg files.
http://forum.kerbalspaceprogram.com/index.php?/topic/50533-112-module-manager-2625-may-19th-where-the-singularity-started/&page=138#comment-2450345

**Comment by TriggerAu** [comment]
Is there an equivalent issue in MM request to handle this?

**Comment by sarbian** [comment]
@enceos did you check if MM reported that KAC cfg invalidate the cache in the log before submitting the bug ? 
@TriggerAu MM store a list and SHA of all the dll & cfg. If anything changes it invalidates its cache and re-patch everything. If you have something in your cfg that changes contantly then it may be better to move the cfg in KerbalAlarmClock/Plugins/PluginData where KSP will not auto load them but you will have to load them by hand...

**Comment by TriggerAu** [comment]
is it KerbalAlarmClock/Plugins/PluginData or KerbalAlarmClock/PluginData ?

And is there any way I can include an MM cfg file to tell MM to ignore that file might be the quickest win?

**Comment by sarbian** [comment]
It is "KerbalAlarmClock\Plugins\PluginData"
And no, I did not add an ignore system because it did not find an easy way to do it yet.

**Comment by TriggerAu** [comment]
kk, I'll put it on the list

**Comment by TriggerAu** [comment]
thanks @sarbian

**Comment by enceos** [comment]
@sarbian yep, because KAC config stores window positions.
