### ISSUE TITLE
Manoeuvre Node alarms are displayed when ship is active even when configured to not display

### ISSUE THREAD

**Issue by AlexSatrapa** [TriggerAu/KerbalAlarmClock#167]
I'm not sure if this is expected behaviour, but when I have KAC to automatically add manoeuvre node alarms, and I have the "specific settings" for all alarm types to not show a message when the ship is active, the alarm will still show while the ship is active.

The main problem for me here is that I also use MechJeb, and between KAC and MechJeb fiddling with time warp, I end up missing manoeuvre nodes (such as adjusting a transfer orbit to enter orbit around the target instead of engaging in a lithobraking manoeuvre) and having to load a save game.

**Comment by TriggerAu** [comment]
Pretty sure this is the one handled by #168 as well. If not can you give me a little more detail/screenshots if thats cool
