### ISSUE TITLE
Method not found: 'TimeWarp.SetRate'

### ISSUE THREAD

**Issue by AlexSatrapa** [TriggerAu/KerbalAlarmClock#169]
I'm not sure what I broke, but over the weekend my KSP and KAC were working fine. Now I've broken something and the KAC window doesn't render properly. I see these errors in the KSP.Log:

```
[LOG 23:16:07.399] 6/22/2016 11:16:07 PM,KerbalAlarmClock,BaseLoadDone. Alarms Count (Should be 0):0
[LOG 23:16:07.399] 6/22/2016 11:16:07 PM,KerbalAlarmClock,ScenarioLoadDone. Alarms Count:0
[EXC 23:16:07.474] MissingMethodException: Method not found: 'TimeWarp.SetRate'.
	KerbalAlarmClock.KerbalAlarmClock.Update ()
[LOG 23:16:07.476] [MessageSystem] Reposition 0.02 11730
[LOG 23:16:07.493] 6/22/2016 11:16:07 PM,KerbalAlarmClock,Contracts System Ready
[EXC 23:16:07.574] MissingMethodException: Method not found: 'TimeWarp.SetRate'.
	KerbalAlarmClock.KerbalAlarmClock.Update ()
[EXC 23:16:07.791] MissingMethodException: Method not found: 'TimeWarp.SetRate'.
	KerbalAlarmClock.KerbalAlarmClock.UpdateDetails ()

	KerbalAlarmClock.KerbalAlarmClock.RepeatingWorker ()

	KSPPluginFramework.MonoBehaviourExtended.RepeatingWorkerWrapper ()
[EXC 23:16:07.792] MissingMethodException: Method not found: 'TimeWarp.SetRate'.
	KerbalAlarmClock.KerbalAlarmClock.Update ()
```

I have no idea where to start debugging, having never built a plugin for KSP.

I've tried deleting KAC and MechJeb, launching the game, starting a new game and then quitting the game, reinstalling the add ons then starting the game again, but the KAC window is still broken. This happens with my existing career game or a brand new career game.

**Comment by WarezCrawler** [comment]
We are all experiencing this on KSP 1.1.3. A recompile might be all that is needed. In the meantime, if we want to use alarmclock we have to do that on KSP 1.1.2.

**Comment by AlexSatrapa** [comment]
Which forum am I missing out on :D

**Comment by gappleto97** [comment]
This one: http://forum.kerbalspaceprogram.com/index.php?/topic/22809-11x-kerbal-alarm-clock-v3630-may-23/
