### ISSUE TITLE
'Delete Alarm' Confirmation always appears to the right of main KAC window

### ISSUE THREAD

**Issue by gavinzac** [TriggerAu/KerbalAlarmClock#170]
Minor issue, but a little frustrating: Unlike the Edit Alarm window and other secondary windows, clicking to delete an alarm with the confirmation required always creates the dialog box to the right of the main KAC window. This means that it will appear offscreen if the KAC window is all the way to the right, or that the buttons may be obscured if not fully to the right.

Appearing 'in front of' the KAC window would be more like expected behaviour (as that's where my cursor would be, and that's where you get these popups in an OS or browser) but just following the same always-on-screen policy as the other secondary windows would solve the problem.

**Comment by TriggerAu** [comment]
Added the common code to make sure it stay on screen
