### ISSUE TITLE
Add Transfer Window Alarm doesn't handle long lists well

### ISSUE THREAD

**Issue by gavinzac** [TriggerAu/KerbalAlarmClock#171]
In some edge cases (e.g. installation of Galactic Neighbourhood mod), long lists of transfer windows stretch the window to below the screen height.

![screenshot 2016-06-28 19 12 44](https://cloud.githubusercontent.com/assets/460483/16413454/a7dd4c72-3d64-11e6-9afa-e0412e727081.png)

**Comment by TriggerAu** [comment]
Added a scrollbar that appears when the list gets too long
