### ISSUE TITLE
Exception related to "HandleKeyStrokes"

### ISSUE THREAD

**Issue by Galenmacil** [TriggerAu/KerbalAlarmClock#180]
This got generated in the VAB when I renamed a design:

[EXC 18:40:48.113] NullReferenceException: Object reference not set to an instance of an object
    KerbalAlarmClock.KerbalAlarmClock.HandleKeyStrokes ()
    KerbalAlarmClock.KerbalAlarmClock.Update ()

**Comment by TriggerAu** [comment]
Should be resolved by PR #179 . Tested OK here
