### ISSUE TITLE
Nullref when "X" key is hit in the VAB

### ISSUE THREAD

**Issue by sick13** [TriggerAu/KerbalAlarmClock#181]
Nullref appears in VAB when hitting "X" Key

[EXC 23:36:14.087] NullReferenceException: Object reference not set to an instance of an object
    KerbalAlarmClock.KerbalAlarmClock.HandleKeyStrokes ()
    KerbalAlarmClock.KerbalAlarmClock.Update ()

**Comment by Galenmacil** [comment]
This is the same issue as https://github.com/TriggerAu/KerbalAlarmClock/issues/180

Happens for a few keys not just X.
