### ISSUE TITLE
errors transfer window in 3.8.2.0

### ISSUE THREAD

**Issue by hanson86** [TriggerAu/KerbalAlarmClock#183]
![kerbal alarm clock error](https://cloud.githubusercontent.com/assets/24504640/21079225/2af0bf04-bf83-11e6-9fef-69faece1f751.png)

when trying to use the transfer window i keep getting the attached error. 

its the first time its been installed so isnt an upgrade on my machine. also happens on 64 and 32 bit versions of the game. i've also tried a re-install and setting a planet as a target but the screen still shows the same

**Comment by TriggerAu** [comment]
Made a super dumb mistake, new version on its way in 15
