### ISSUE TITLE
Option "Hide when paused" does nothing

### ISSUE THREAD

**Issue by jd284** [TriggerAu/KerbalAlarmClock#184]
The windows are always hidden when paused regardless how this option is set.

The value of this option is checked in DrawGUI(), but this function isn't even called when paused because the caller does its own check and skips it when the game is paused.

Either call DrawGUI() always, or add another check for this option in OnGUIEvery().

**Comment by TriggerAu** [comment]
Found this one, change in loogic previously regressed it - codes commited
