### ISSUE TITLE
Delete .loadmeta files when rotating backups

### ISSUE THREAD

**Issue by fat-lobyte** [TriggerAu/KerbalAlarmClock#189]
KAC allows to specify a maximum number of backups of the persistent and the quicksave files to keep. However, when deleting the .sfs files, the .loadmeta files (that are created since KSP 1.2) are left there.

It would be nice if the .loadmeta files would be deleted along with the .sfs files.

**Comment by 81ninja** [comment]
That's not happening here (v3.8.4.0 installed through CKAN). Only the .sfs file backups stay on the save folder.

**Comment by TriggerAu** [comment]
Updated the Purge routine to also clear loadmeta's - there is a check in core game as well, but better safe than sorry
