### ISSUE TITLE
KAC constantly throwing MissingFieldException

### ISSUE THREAD

**Issue by CF314** [TriggerAu/KerbalAlarmClock#191]
Since updating KSP to 1.3 KAC is filling my log with something like this:
```
[EXC 18:28:57.086] MissingFieldException: Field '.KeyBinding.primary' not found.
	KerbalAlarmClock.KerbalAlarmClock.Update ()
[EXC 18:28:57.109] MissingFieldException: Field '.KeyBinding.primary' not found.
	KerbalAlarmClock.KerbalAlarmClock.Update ()
[EXC 18:28:57.128] MissingFieldException: Field '.KeyBinding.primary' not found.
	KerbalAlarmClock.KerbalAlarmClock.Update ()
[EXC 18:28:57.159] MissingFieldException: Field '.KeyBinding.primary' not found.
	KerbalAlarmClock.KerbalAlarmClock.Update ()
```
This has not had any effect on my gameplay, but it is annoying and seems like an incompatability with the new KSP version. I've only included four log entries, but this constantly happens while a save is loaded (You're actually playing, not in Main Menu etc.).

**Comment by Olympic1** [comment]
KAC isn't released yet for KSP 1.3

**Comment by CF314** [comment]
I know. It's just so that the incompatability is known and can be fixed in future versions.

**Comment by TriggerAu** [comment]
Twill be fixed in a little
