### ISSUE TITLE
ClickThrough issues

### ISSUE THREAD

**Issue by BloodyRain2k** [TriggerAu/KerbalAlarmClock#192]
Is there a chance to get it fixed that clicking in the KAC windows also clicks whatever happens to be behind it?
This is extremely annoying in the map view for me because I have so many orbits all over the screen most of the time that it's nearly impossible to NOT click something : (

One time I even accidentally switched vessels because the two clicks I needed to make dismiss an alarm (2nd click was for the "close on delete" check) due to it's orbit being behind the checkbox and the switch to vessel button happening to come up behind the close button for the KAC dialog.

**Comment by rspeed** [comment]
I think there has been a regression. In the current versions of the mod and KSP clicks are passing through KAC windows.
