### ISSUE TITLE
Permit disabling the arrows in the map view

### ISSUE THREAD

**Issue by RalfJung** [TriggerAu/KerbalAlarmClock#193]
I find these arrows that the alarm clock adds in the map view fairly irritating -- in particular, when there's already lots of things going on there, they add a lot of additional visual noise. I also don't use this feature often enough to make them useful; usually I prefer using the stock "Warp to".

It would be great if these arrows could be toggled in the settings.

**Comment by TriggerAu** [comment]
It already is configurable, pretty sure the path is Settings->Specifics->Select Alarm Type: "Warp To Alarms" -> Enable WarpTo 

uncheck tht and your away

**Comment by RalfJung** [comment]
Ah, there it is, thanks!

I had entirely missed the fact that the drop-down in "specifics" selects between totally different sets of configurations; it acts more like tabs than like a normal drop-down.
