### ISSUE TITLE
Support Request: KACWrapper

### ISSUE THREAD

**Issue by mwerle** [TriggerAu/KerbalAlarmClock#197]
Hi,
First of all, this is really awesome and on the whole very easy to use!

2 questions though:

**1. Why return the alarm ID instead of an object reference?**

The example usage is as follows:
```
    //Create a raw alarm 15 mins from now game time and get the id back
    String aID = KACWrapper.KAC.CreateAlarm(KACWrapper.KACAPI.AlarmTypeEnum.Raw, "New Alarm", Planetarium.GetUniversalTime() + 900);
     
    if (aID !="") {
        //if the alarm was made get the object so we can update it
        KACWrapper.KACAPI.KACAlarm a = KACWrapper.KAC.Alarms.First(z=>z.ID==aID);
        ...
```

Considering the user basically has to retrieve the alarm object using an expensive predicate search anyway in order to set the remaining data on the alarm, why not return the alarm object (or null) straightaway? Presumably CreateAlarm() has that reference at hand to avoid the search..

**2. Alarm margin doesn't seem to do anything?**

I create an alarm, passing in the alarm time, and then set the alarm margin:

```
            String aID = KACWrapper.KAC.CreateAlarm(KACWrapper.KACAPI.AlarmTypeEnum.ScienceLab, "NEOS Alarm", Planetarium.GetUniversalTime() + timeRemaining);
            ....
            KACWrapper.KACAPI.KACAlarm a = KACWrapper.KAC.Alarms.Find(z=>z.ID==aID);
            a.AlarmMargin = 30; /* Fire 30 seconds before due time */
```

but in-game, the alarm seems to fire at the calculated time, not 30s (originally 3m) beforehand.

Is this a bug, or is there a trick to using this?  I can, of course, simply subtract 30s from my 'timeRemaining' to achieve the same result, but then in-game the user could not change the margin if they so desire.

Thanks, and many thanks for not only an absolutely necessary mod, but also a great API to interface with it!

 - Micha.

**Comment by TriggerAu** [comment]
The short answers are:
1) I dont recall as it was a long time ago - I have a vague recollection it was cause using reflection instead of a hard reference
2) That sounds like a bug...

Had a bit of a look and the margin one appears to be because of the alarm type - it works for a raw alarm here for example, but the science lab type alarm doesnt have a margin as it fires when the lab is full. 

Are you able to use a Raw alarm for that one and see how you go. Changing the science lab alarm Ill have to dig into the PR code that came with

**Comment by mwerle** [comment]
1. No worries; of course if there's a technical reason behind it it's fully understandable.  Was just asking from both a laziness perspective (extra user-code which can cause bugs - I actually just ironed out a NRE in mine) as well as a performance perspective.

2. Yes, I can use raw alarms, but then I don't get the nifty science flask icon :)  Unless I've missed something and it's possible to set the icon on raw alarms? I've since experimented a bit, and I don't think an alarm margin is actually all that useful for the experiments, so I'm defaulting them to '0' now anyway. Still, if you get bored, you might want to see about either supporting margins on the science alarm, or letting the API set an icon on raw alarms.

Thanks again for a most awesome and necessary mod :)

**Comment by TriggerAu** [comment]
Oh my goodness, I just realised why the margin doesnt work for you and I have tyo apologise profusely as I shoulda seen that from the code. The UT of the alarm is when it fires, the Margin is how far after that time the event actually happens - it works like that cause the margin didnt exist when teh project started and was added afterwards. 

So to have a science alarm fire 30 secs before the event you set the UT to be that time and set the margin so the indication of the event is at the correct time

```
String aID = KACWrapper.KAC.CreateAlarm(KACWrapper.KACAPI.AlarmTypeEnum.ScienceLab, "NEOS Alarm", Planetarium.GetUniversalTime() + timeRemaining - 30);
....
KACWrapper.KACAPI.KACAlarm a = KACWrapper.KAC.Alarms.Find(z=>z.ID==aID);
a.AlarmMargin = 30; /* Fire 30 seconds before due time */
```

I am sooo sorry that I missed that first time round (and it wasnt the PR code) and only just got 1 and 1 to make 2 just now

**Comment by TriggerAu** [comment]
Ill close this one now, but if that doesnt work let me know
