### ISSUE TITLE
Update on 1.4.1.2089?

### ISSUE THREAD

**Issue by cookins** [TriggerAu/KerbalAlarmClock#199]
hey
will mod work for last 1.4.1.2089?

**Comment by theonegalen** [comment]
Try it. Probably not.

It is considered very bad form to badger mod authors for updates and has lead to some mod authors quitting modding in the past. They do it for free, so whenever they have time is good.

**Comment by a-m-s** [comment]
See #198

**Comment by TriggerAu** [comment]
is coming
