### ISSUE TITLE
KSP cursor disappears after mousing over Kerbal Alarm Clock

### ISSUE THREAD

**Issue by emk** [TriggerAu/KerbalAlarmClock#200]
Thank you for a very interesting-looking KSP mod! It looks like it will be very useful.

- OS: Ubuntu 17.10.
- KSP: 1.4.1.
- KerbalAlarmClock: 3.9.0.0 (I think, it was up-to-date on 18 March via CKAN).

**To reproduce:** Open Kerbal Alarm Clock window in flight mode. Move mouse over the KAC window and buttons.

**What happens:** The standard KSP cursor becomes invisible. The cursor _works_, but I can't see where it is, so I need to move it around blindly. Moving off the KAC window, exiting flight mode, etc., do not fix it. The only way to get the cursor back is to completely quit KSP and restart.

Interestingly, there are a few places in KSC that use a custom cursor. In these cases, the cursor will reappear temporarily while the custom cursor is set, and then disappear again. Also, moving the cursor outside of the KSP window will show a normal OS cursor.

**What should happen:** I should see a normal cursor.

I'm happy to provide any further debugging information. This isn't urgent for me, but I thought you would like to know in case it affects other users.

**Comment by no-sense** [comment]
I am having the exact same issue. It doesn't happen every time I hover over it but just moving in and out of the KAC window a few times does the trick.
Besides that, the original poster is entirely correct in his description.

 -  OS: Ubuntu 16.04 LTS
 -  KSP: 1.4.1.
 -  KerbalAlarmClock: 3.9.0.0 (downloaded and installed manually)

I have been using KAC for a few years now - this is the first time I encounter any issue. It's an annoying one though, I even need to set an alarm in the blind...
Like the original poster, I am willing to provide any information I can.

**Comment by emk** [comment]
Is it possible that KAC is trying to use a cursor name that exists on some platforms, but not on Linux? I should look at the code.

**Comment by no-sense** [comment]
Just another tidbit of information: The cursor disappearance only happens when mousing over the KAC main window. Popups of expired timers work without a problem. Also if I managed to click on the Add (alarm) button and the mouse did not disappear, it won't disappear either when filling in the alarm details in the new alarm popup window no matter how often I mouse in and out of the window.

**Comment by IncorrectValue** [comment]
I'm having the same problem.
- OS Debian 9.4
- KSP 1.4.1.2089
- KerbalAlarmClock: 3.9.0.0

Cursor disappears after crossing the right edge of the Alarm Clock window - when on the edge, a different resize icon is displayed, but when moved further the original cursor doesn't reappear.
I see no errors in KSP.log file when that happens.

**Comment by SERVCUBED** [comment]
I also have the same issue. I can see the resize cursor when moving the mouse over the right window border, however the original cursor is not restored. I will be happy to provide log files or testing if needed.  

- Arch Linux 4.15.11-1
- KSP 1.4.1.2089
- KerbalAlarmClock: 3.9.0.0

Upon brief inspection, this may be a problem with `ClearCustomCursor()` in `KerbalAlarmClock_Window.cs` which calls [SetCursor](https://docs.unity3d.com/ScriptReference/Cursor.SetCursor.html), a native call in the Unity engine.

**Comment by TriggerAu** [comment]
Removed the custom cursor calls from KAC for Linux issues.

Thanks all for the detailed info and feedback

**Comment by emk** [comment]
Thank you, this is excellent!
