### ISSUE TITLE
Request: Integration with Kronometer

### ISSUE THREAD

**Issue by gordonfpanam** [TriggerAu/KerbalAlarmClock#202]
Kopernicus supports changing the home world to one with a different orbital period and rotation period than Kerbin (6h) or Earth (24h). For instance, Eve has 22h, 22m days and 69d (Eve), 6.5h years. [Kronometer](https://github.com/StollD/Kronometer) changes the game clock to match the home world's rotation and orbital periods, allowing for 22h 22m days and 69d years in-game in the case of Eve.

Both Kerbal Alarm Clock and Transfer Window Planner seem to use Kerbin time or Earth time only depending on the game's General settings.

Is there an option to use the Kronometer clock setting for displaying times, or could one be included?

**Comment by TriggerAu** [comment]
Should be along shortly when I merge #211
