### ISSUE TITLE
Feature request: scale with KSP UI Scale configuration

### ISSUE THREAD

**Issue by drakesiard** [TriggerAu/KerbalAlarmClock#204]
I'm running KSP at a high resolution with UI scale set to 150%, and the KAC text is small and difficult to read. How hard would it be to make KAC read the scaling from the game's configuration and use it as well?

**Comment by TriggerAu** [comment]
Added Scaling to the draw methods and also two settings to settings file so you can use the games scaling or override your own
- UIScaleOverride = false by default so it uses the overall scaling
- UIScaleValue = value to use if you set the above true
