### ISSUE TITLE
KAC hide window sometimes gets reversed

### ISSUE THREAD

**Issue by linuxgurugamer** [TriggerAu/KerbalAlarmClock#206]
The following sequence causes KAC to be hidden in flight and shown while the UI is hidden:

Hit escape to pause the game
Hit F2 to hide the UI
Hit escape

Game will unpause, but the KAC window is hidden.   Now hit F2 to hide the UI, and KAC will appear

**Comment by linuxgurugamer** [comment]
Hitting the toolbar button doesn't do anything.  Repeating the sequence will fix it.

**Comment by TriggerAu** [comment]
Fix is in develop now

**Comment by linuxgurugamer** [comment]
Great
