### ISSUE TITLE
Update to 1.7

### ISSUE THREAD

**Issue by HerrX2000** [TriggerAu/KerbalAlarmClock#225]
1.7 "Room to Maneuver" has been released. It would be nice to see the addon beeing updated to the new version. I do not know if there are any compatibility issues.

**Comment by tschaerni** [comment]
I'm using KAC atm under 1.7. It looks that it works, I can't see any bugs right now.

**Comment by Brettdah** [comment]
great news, but may be it need a recompile to be displayed as 1.7 friendly in CKAN I can see Max KSP version 1.6.9 ;)
I will try the mod right away I wanted to have something like that for my contracts :)
