### ISSUE TITLE
1.8 Compatability

### ISSUE THREAD

**Issue by Ruedii** [TriggerAu/KerbalAlarmClock#234]
Mod needs some updating for KSP 1.8.x comparability according to forum.

This is a singular goal and should be treated as a metabug for smaller bugs related to KSP 1.8.x.

Please mark this bug as dependent for any KSP 1.8.x issues you encounter and comment below a brief summary of what issues you have.

**Comment by sorinj** [comment]
Not sure if this was intentional or not, but the binaries are are missing in the v3.12.0.0 release. The previous releases included the binary assets, which could be downloaded and drop installed in KSP.
