### ISSUE TITLE
The 1.8 compatibility release is missing a binary

### ISSUE THREAD

**Issue by willwill2will54** [TriggerAu/KerbalAlarmClock#235]
You appear to have forgotten the binary for the 3.12 release. It is therefore being ignored by the CKAN indexer. Simply adding one in retroactively before you make the next release would solve the problem.

**Comment by TriggerAu** [comment]
Interesting, its listed in the release when I edit, but not as an actual download link

Ive reuploaded it, see how that goes

**Comment by willwill2will54** [comment]
It worked! Its indexed on CKAN and I can remove the manual install and return to mod managed bliss.
