### ISSUE TITLE
Contract alarms vanish on situation change

### ISSUE THREAD

**Issue by lwho** [TriggerAu/KerbalAlarmClock#92]
Using Kerbal Alarm Clock 3.1.0.0 on KSP 0.90.0 Linux x64 all types of contract alarms do not work. When added, they appear in the Alarm List, but as soon as the situation changes (e.g. when switching from Flight to Space Center) all contract alarms have disappeared.

This applies to both alarms for accepted and non-accepted contracts and no matter whether "Attach to vessel" was activated.

**Comment by lwho** [comment]
Sorry to say that, but it's still not really working.

I now have situation changes that often take longer than 5s and then the contract alarms still vanish.

By luck, when looking at the source of the Contract Science Modifier plugin (http://forum.kerbalspaceprogram.com/threads/101322-0-90-0-25-Contract-Science-Modifier-(v0-3)-2014-12-09), I stumbled over the following line of code:

```C#
GameEvents.Contract.onContractsLoaded.Add(contractsLoaded);
```

and looking at the Assembly browser of this class in monodevelop, the ```GameEvents.Contract``` class has a few more callbacks to offer:

```C#
public static class Contract
{
	//
	// Static Fields
	//
	public static EventData<Contract> onOffered;
	public static EventVoid onContractsLoaded;
	public static EventData<Contract, ContractParameter> onParameterChange;
	public static EventData<Contract> onFinished;
	public static EventData<Contract> onCancelled;
	public static EventData<Contract> onFailed;
	public static EventData<Contract> onCompleted;
	public static EventData<Contract> onDeclined;
	public static EventData<Contract> onAccepted;
	public static EventVoid onContractsListChanged;
}
```

Creating handlers for those events might be the right direction for a stable solution.

**Comment by TriggerAu** [comment]
Didnt even know that one was there - will look at it now
